import { ArrowRight, CheckCircle2, Info, Minus, Plus } from 'lucide-react';
import { FormEvent, useState } from 'react';
import { Link, Navigate, useParams } from 'react-router-dom';
import { Button } from '@/components/ui/Button';
import { api } from '@/services/api';
import { soldierActions } from './actions';
import { SignaturePad } from './SignaturePad';

const text = (data: FormData,key:string) => { const value=data.get(key); return typeof value==='string'?value.trim():''; };
const departments = ['מחלקה 1','מחלקה 2','מחלקה 3','מפל״ג','מסופחים'];
const equipment = [{id:'helmet',name:'קסדה',max:10},{id:'vest',name:'ווסט',max:10},{id:'mitznefet',name:'מצנפת',max:10},{id:'knee',name:'ברכיות',max:10},{id:'mags',name:'מחסניות',max:20}];

function IdentityFields(){return <div className="form-grid">
  <label><span>שם מלא</span><input name="fullName" autoComplete="name" required placeholder="שם פרטי ומשפחה" /></label>
  <label><span>מספר אישי</span><input name="personalId" inputMode="numeric" dir="ltr" required minLength={5} maxLength={9} placeholder="מספר אישי" /></label>
  <label><span>טלפון</span><input name="phone" inputMode="tel" dir="ltr" autoComplete="tel" required pattern="05[0-9]{8}" placeholder="05X-XXXXXXX" /></label>
  <label><span>מחלקה</span><select name="department" required defaultValue=""><option value="" disabled>בחרו מחלקה</option>{departments.map(x=><option key={x}>{x}</option>)}</select></label>
</div>}
function Section({n,title,sub,children}:{n:number;title:string;sub:string;children:React.ReactNode}){return <div className="form-section"><header><span>{n}</span><div><h2>{title}</h2><p>{sub}</p></div></header>{children}</div>}

function EquipmentForm({done}:{done:()=>void}){
  const [quantities,setQuantities]=useState<Record<string,number>>({helmet:1,vest:1,mitznefet:1,knee:1,mags:5});
  const [selected,setSelected]=useState<Record<string,boolean>>({helmet:true,vest:true,mitznefet:true,knee:true,mags:true});
  const [signature,setSignature]=useState<Blob|null>(null); const [busy,setBusy]=useState(false); const [error,setError]=useState('');
  const submit=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault(); if(!signature){setError('יש לחתום בתוך מסגרת החתימה');return;} setBusy(true);setError('');
    try{const data=new FormData(event.currentTarget); const sig=await api.uploadDocument('signature',signature,'signature.png');
      const civilianFile=data.get('civilianDocument'); if(!(civilianFile instanceof File)||!civilianFile.size) throw new Error('יש לצלם או להעלות את רישיון הנהיגה');
      const civ=await api.uploadDocument('civilian_license',civilianFile,civilianFile.name);
      const licenses:Record<string,unknown>[]=[{type:'civilian',number:text(data,'civilianNumber'),expiresAt:new Date(text(data,'civilianExpiry')).getTime(),documentObjectKey:civ.key,documentName:civ.name,documentType:civ.type,documentSize:civ.size}];
      const militaryFile=data.get('militaryDocument'); const militaryNumber=text(data,'militaryNumber'); const militaryExpiry=text(data,'militaryExpiry');
      if(militaryFile instanceof File&&militaryFile.size){const mil=await api.uploadDocument('military_license',militaryFile,militaryFile.name);licenses.push({type:'military',number:militaryNumber,expiresAt:new Date(militaryExpiry).getTime(),documentObjectKey:mil.key,documentName:mil.name,documentType:mil.type,documentSize:mil.size});}
      await api.createEquipmentSignature({fullName:text(data,'fullName'),personalId:text(data,'personalId'),phone:text(data,'phone'),department:text(data,'department'),weaponSerial:text(data,'weaponSerial'),amralSerial:text(data,'amralSerial'),scopeSerial:text(data,'scopeSerial'),note:text(data,'note'),signatureObjectKey:sig.key,licenses,items:equipment.filter(x=>selected[x.id]).map(x=>({itemId:x.id,quantity:quantities[x.id]}))}); done();
    }catch(cause){setError(cause instanceof Error?cause.message:'שליחת החתימה נכשלה');}finally{setBusy(false)}};
  return <form className="public-form" onSubmit={submit}>
    <Section n={1} title="פרטים אישיים ורישיון" sub="הפרטים יפתחו כרטיס חייל במערכת."><IdentityFields/><div className="form-grid license-fields">
      <label><span>מספר רישיון נהיגה</span><input name="civilianNumber" required dir="ltr" placeholder="מספר רישיון" /></label>
      <label><span>תוקף רישיון</span><input name="civilianExpiry" type="date" required /></label>
      <label className="field-wide file-field"><span>צילום רישיון נהיגה</span><input name="civilianDocument" type="file" accept="image/*,application/pdf" capture="environment" required/><small>צילום מהמצלמה או קובץ, עד 3MB</small></label>
      <label><span>מספר רישיון צבאי <em>לא חובה</em></span><input name="militaryNumber" dir="ltr" /></label>
      <label><span>תוקף צבאי <em>לא חובה</em></span><input name="militaryExpiry" type="date" /></label>
      <label className="field-wide file-field"><span>צילום רישיון צבאי <em>לא חובה</em></span><input name="militaryDocument" type="file" accept="image/*,application/pdf" capture="environment" /></label>
    </div></Section>
    <Section n={2} title="נשק וציוד" sub="בחרו רק ציוד שקיבלתם ועדכנו כמות מדויקת."><div className="form-grid serial-fields"><label><span>מספר נשק <em>לא חובה</em></span><input name="weaponSerial" dir="ltr" /></label><label><span>אמר״ל <em>לא חובה</em></span><input name="amralSerial" dir="ltr" /></label><label><span>כוונת <em>לא חובה</em></span><input name="scopeSerial" dir="ltr" /></label></div><div className="equipment-picker">{equipment.map(item=>{const quantity=quantities[item.id]??1;return <article className={selected[item.id]?'is-selected':''} key={item.id}><label><input type="checkbox" checked={!!selected[item.id]} onChange={e=>setSelected(v=>({...v,[item.id]:e.target.checked}))}/><strong>{item.name}</strong></label><div className="quantity-control"><button type="button" disabled={!selected[item.id]||quantity<=1} onClick={()=>setQuantities(v=>({...v,[item.id]:(v[item.id]??1)-1}))}><Minus/></button><span>{selected[item.id]?quantity:0}</span><button type="button" disabled={!selected[item.id]||quantity>=item.max} onClick={()=>setQuantities(v=>({...v,[item.id]:(v[item.id]??1)+1}))}><Plus/></button></div></article>})}</div><label className="field-wide"><span>הערה <em>לא חובה</em></span><textarea name="note" placeholder="ציוד חריג או מידע למנהל הציוד"/></label></Section>
    <Section n={3} title="אישור וחתימה" sub="עברו על הפרטים וחתמו באצבע או בעכבר."><SignaturePad onChange={setSignature}/><label className="consent-check"><input type="checkbox" required/><span>אני מאשר שקיבלתי את הציוד המפורט ומתחייב לשמור עליו ולהחזירו.</span></label></Section>
    {error&&<div className="login-error" role="alert">{error}</div>}<div className="public-form-actions"><Button variant="primary" type="submit" disabled={busy}>{busy?'שומר חתימה…':'שליחת חתימה לאישור'}</Button><Link className="button" to="/">ביטול</Link></div>
  </form>;
}

function SimpleOperationalForm({kind,done}:{kind:'deposit'|'fault';done:()=>void}){const[busy,setBusy]=useState(false);const[error,setError]=useState('');const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setBusy(true);setError('');const d=new FormData(e.currentTarget);try{const base={fullName:text(d,'fullName'),personalId:text(d,'personalId'),phone:text(d,'phone'),department:text(d,'department')};if(kind==='deposit')await api.createWeaponDeposit({...base,weaponSerial:text(d,'weaponSerial'),amralSerial:text(d,'amralSerial'),scopeSerial:text(d,'scopeSerial'),note:text(d,'note')});else await api.createBuildingFault({...base,location:text(d,'location'),category:text(d,'category'),description:text(d,'description')});done()}catch(c){setError(c instanceof Error?c.message:'שליחת הטופס נכשלה')}finally{setBusy(false)}};return <form className="public-form" onSubmit={submit}><Section n={1} title="זיהוי ויצירת קשר" sub="כדי שנוכל לשייך את הבקשה ולחזור אליכם."><IdentityFields/></Section><Section n={2} title={kind==='deposit'?'פרטי הנשק לאפסון':'פרטי תקלת הבינוי'} sub={kind==='deposit'?'אין להשאיר נשק לפני אישור וקליטה של מנהל הארמון.':'ציינו מיקום מדויק ותיאור שיעזור לטפל מהר.'}><div className="form-grid">{kind==='deposit'?<><label><span>מספר נשק</span><input name="weaponSerial" dir="ltr" required/></label><label><span>אמר״ל <em>לא חובה</em></span><input name="amralSerial" dir="ltr"/></label><label><span>כוונת <em>לא חובה</em></span><input name="scopeSerial" dir="ltr"/></label><label className="field-wide"><span>הערה <em>לא חובה</em></span><textarea name="note"/></label></>:<><label><span>מיקום התקלה</span><input name="location" required placeholder="מבנה, קומה וחדר"/></label><label><span>קטגוריה</span><select name="category" required defaultValue=""><option value="" disabled>בחרו סוג</option>{['חשמל','מים','מיזוג','דלתות ומנעולים','תברואה','אחר'].map(x=><option key={x}>{x}</option>)}</select></label><label className="field-wide"><span>תיאור התקלה</span><textarea name="description" minLength={10} required placeholder="מה קרה, מתי הבחנתם ומה חומרת התקלה"/></label></>}</div></Section>{kind==='deposit'&&<div className="privacy-note"><Info/><span><strong>חשוב:</strong> הבקשה אינה אישור מסירה. המתינו לאישור מנהל הארמון.</span></div>}{error&&<div className="login-error">{error}</div>}<div className="public-form-actions"><Button variant="primary" type="submit" disabled={busy}>{busy?'שולח…':'שליחה לאישור'}</Button><Link className="button" to="/">ביטול</Link></div></form>}

function RefuelForm({done}:{done:()=>void}){const[busy,setBusy]=useState(false);const[error,setError]=useState('');const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setBusy(true);setError('');const d=new FormData(e.currentTarget);try{const file=d.get('receipt');if(!(file instanceof File)||!file.size)throw new Error('יש לצלם או להעלות קבלת תדלוק');const receipt=await api.uploadDocument('fuel_receipt',file,file.name);await api.createRefuelReport({fullName:text(d,'fullName'),personalId:text(d,'personalId'),phone:text(d,'phone'),department:text(d,'department'),vehicleNumber:text(d,'vehicleNumber'),cardNumber:text(d,'cardNumber'),litres:Number(text(d,'litres')),odometer:Number(text(d,'odometer')),note:text(d,'note'),receiptObjectKey:receipt.key});done()}catch(c){setError(c instanceof Error?c.message:'שליחת הדיווח נכשלה')}finally{setBusy(false)}};return <form className="public-form" onSubmit={submit}><Section n={1} title="פרטי המדווח" sub="הדיווח יישמר ביומן התדלוק."><IdentityFields/></Section><Section n={2} title="פרטי התדלוק" sub="הדיווח יאושר על ידי מנהל הרכב ואז יקוזז מהכרטיס."><div className="form-grid"><label><span>מספר רכב</span><input name="vehicleNumber" required dir="ltr"/></label><label><span>מספר כרטיס תדלוק</span><input name="cardNumber" required dir="ltr"/></label><label><span>כמות בליטרים</span><input name="litres" type="number" min="0.1" max="500" step="0.1" required dir="ltr"/></label><label><span>מד אוץ <em>לא חובה</em></span><input name="odometer" type="number" min="0" dir="ltr"/></label><label className="field-wide file-field"><span>צילום קבלה</span><input name="receipt" type="file" accept="image/*,application/pdf" capture="environment" required/></label><label className="field-wide"><span>הערה <em>לא חובה</em></span><textarea name="note"/></label></div></Section>{error&&<div className="login-error">{error}</div>}<div className="public-form-actions"><Button variant="primary" type="submit" disabled={busy}>{busy?'שולח…':'שליחת דיווח תדלוק'}</Button><Link className="button" to="/">ביטול</Link></div></form>}

function ShortageForm({done}:{done:()=>void}){const[busy,setBusy]=useState(false);const[error,setError]=useState('');const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setBusy(true);const d=new FormData(e.currentTarget);try{await api.createSubmission({actionType:'shortage',fullName:text(d,'fullName'),personalId:text(d,'personalId'),phone:text(d,'phone'),department:text(d,'department'),payload:{request:text(d,'request'),note:text(d,'note')}});done()}catch(c){setError(c instanceof Error?c.message:'שליחת הבקשה נכשלה')}finally{setBusy(false)}};return <form className="public-form" onSubmit={submit}><Section n={1} title="פרטי המבקש" sub="כדי שנוכל לחזור אליכם."><IdentityFields/></Section><Section n={2} title="מה חסר?" sub="פרטו פריטים, כמויות והסיבה לבקשה."><div className="form-grid"><label className="field-wide"><span>ציוד וכמות</span><textarea name="request" required minLength={3}/></label><label className="field-wide"><span>הערה <em>לא חובה</em></span><textarea name="note"/></label></div></Section>{error&&<div className="login-error">{error}</div>}<div className="public-form-actions"><Button variant="primary" type="submit" disabled={busy}>{busy?'שולח…':'שליחת בקשה'}</Button></div></form>}

export function SoldierActionPage(){const{actionId}=useParams();const action=soldierActions.find(x=>x.id===actionId);const[submitted,setSubmitted]=useState(false);if(!action||!actionId)return <Navigate to="/" replace/>;const Icon=action.icon;const done=()=>setSubmitted(true);return <section className="action-page"><Link className="back-link" to="/"><ArrowRight/> חזרה לכל הפעולות</Link><header className="action-page-header"><span className={`action-card-icon accent-${action.accent}`}><Icon/></span><div><span className="eyebrow">טופס לחייל</span><h1>{action.title}</h1><p>{action.description}</p></div></header>{submitted?<div className="submission-card" role="status"><span><CheckCircle2/></span><h2>{actionId==='equipment'?'החתימה נשלחה לאישור':'הפרטים נקלטו'}</h2><p>{actionId==='deposit'?'מנהל הארמון יאשר את הקליטה. אין להשאיר את הנשק לפני האישור.':'הבקשה נשמרה והועברה למנהל המערכת.'}</p><Link className="button button-primary" to="/">חזרה למסך הראשי</Link></div>:actionId==='equipment'?<EquipmentForm done={done}/>:actionId==='deposit'||actionId==='fault'?<SimpleOperationalForm kind={actionId} done={done}/>:actionId==='refuel'?<RefuelForm done={done}/>:<ShortageForm done={done}/>}</section>}
