import type { Soldier } from './soldier.schema';

export const soldierFixtures: Soldier[] = [
  {
    id: 's-1',
    fullName: 'אור שמחון',
    personalId: '5817533',
    department: 'מפל״ג',
    phone: '0521234573',
    approvalStatus: 'approved',
    equipmentStatus: 'outside',
    approvedAt: '2026-08-06T20:15:00Z',
    messageSentAt: '2026-08-06T20:18:00Z',
    civilianLicense: {
      number: '344343',
      expiresAt: '2030-05-02',
      approved: true,
      documentName: 'civil-license.jpg',
    },
    militaryLicense: {
      number: '344343',
      expiresAt: '2030-05-02',
      approved: true,
      documentName: 'military-license.jpg',
    },
    equipment: [
      { id: 'helmet', name: 'קסדה', issued: 1, returned: 0 },
      { id: 'vest', name: 'ווסט', issued: 1, returned: 0 },
      { id: 'mags', name: 'מחסניות', issued: 5, returned: 2 },
    ],
    note: 'הודעת רישום נשלחה.',
  },
  {
    id: 's-2',
    fullName: 'נועם לוי',
    personalId: '6749211',
    department: 'מחלקה 1',
    phone: '0547654321',
    approvalStatus: 'pending',
    equipmentStatus: 'partial',
    approvedAt: null,
    messageSentAt: null,
    civilianLicense: {
      number: '771204',
      expiresAt: '2027-01-18',
      approved: true,
      documentName: null,
    },
    militaryLicense: { number: '', expiresAt: null, approved: false, documentName: null },
    equipment: [
      { id: 'helmet', name: 'קסדה', issued: 1, returned: 1 },
      { id: 'vest', name: 'ווסט', issued: 1, returned: 0 },
    ],
    note: '',
  },
  {
    id: 's-3',
    fullName: 'יובל כהן',
    personalId: '7421098',
    department: 'מחלקה 2',
    phone: '0503334455',
    approvalStatus: 'approved',
    equipmentStatus: 'returned',
    approvedAt: '2026-08-01T10:00:00Z',
    messageSentAt: '2026-08-01T10:04:00Z',
    civilianLicense: { number: '', expiresAt: null, approved: false, documentName: null },
    militaryLicense: {
      number: '909118',
      expiresAt: '2028-11-30',
      approved: true,
      documentName: 'military.jpg',
    },
    equipment: [{ id: 'helmet', name: 'קסדה', issued: 1, returned: 1 }],
    note: 'הציוד הוחזר במלואו.',
  },
  {
    id: 's-4',
    fullName: 'רוני אברהם',
    personalId: '6108842',
    department: 'מחלקה 3',
    phone: '0538822110',
    approvalStatus: 'approved',
    equipmentStatus: 'outside',
    approvedAt: '2026-07-29T15:30:00Z',
    messageSentAt: null,
    civilianLicense: {
      number: '667821',
      expiresAt: '2026-09-10',
      approved: true,
      documentName: 'license.jpg',
    },
    militaryLicense: { number: '', expiresAt: null, approved: false, documentName: null },
    equipment: [
      { id: 'mags', name: 'מחסניות', issued: 6, returned: 0 },
      { id: 'knee', name: 'ברכיות', issued: 2, returned: 0 },
    ],
    note: '',
  },
];
