import { Check, ChevronDown, Download, Eye, Minus, Plus, RefreshCw, RotateCcw, X } from 'lucide-react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Fragment, useMemo, useState } from 'react';
import { Avatar } from '@/components/ui/Avatar';
import { Button } from '@/components/ui/Button';
import { IconButton } from '@/components/ui/IconButton';
import { SearchInput } from '@/components/ui/SearchInput';
import { StatusBadge } from '@/components/ui/StatusBadge';
import { api, type EquipmentSignature } from '@/services/api';

type Filter='all'|'pending'|'outside'|'returned';
const totalOut=(row:EquipmentSignature)=>row.lines.reduce((sum,line)=>sum+line.issued_quantity-line.returned_quantity,0);
const statusLabel=(row:EquipmentSignature)=>row.status==='pending'?'ממתין לאישור':totalOut(row)===0?'הוחזר במלואו':row.lines.some(x=>x.returned_quantity>0)?'הוחזר חלקית':'ציוד בחוץ';
const csv=(rows:EquipmentSignature[])=>{const data=[['שם','מ״א','מחלקה','טלפון','סטטוס','ציוד בחוץ'],...rows.map(x=>[x.full_name,x.personal_id,x.department,x.phone,statusLabel(x),String(totalOut(x))])];const content='\uFEFF'+data.map(r=>r.map(v=>`"${v.replaceAll('"','""')}"`).join(',')).join('\n');const url=URL.createObjectURL(new Blob([content],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='armory-soldiers.csv';a.click();URL.revokeObjectURL(url)};

export function SoldiersPage(){const client=useQueryClient();const[query,setQuery]=useState('');const[filter,setFilter]=useState<Filter>('all');const[expanded,setExpanded]=useState<string|null>(null);const[notice,setNotice]=useState('');
  const signatures=useQuery({queryKey:['equipment-signatures'],queryFn:api.equipmentSignatures});
  const mutate=useMutation({mutationFn:({id,input}:{id:string;input:Record<string,unknown>})=>api.updateEquipmentSignature(id,input),onSuccess:async()=>{await client.invalidateQueries({queryKey:['equipment-signatures']});setNotice('הפעולה נשמרה בהצלחה.')}});
  const visible=useMemo(()=>{const q=query.trim().toLowerCase();return(signatures.data?.items??[]).filter(row=>(!q||`${row.full_name} ${row.personal_id} ${row.department} ${row.phone}`.toLowerCase().includes(q))&&(filter==='all'||filter==='pending'&&row.status==='pending'||filter==='outside'&&row.status==='approved'&&totalOut(row)>0||filter==='returned'&&row.status==='approved'&&totalOut(row)===0))},[signatures.data,query,filter]);
  return <section className="page soldiers-page compact-page"><header className="page-title"><div><span className="eyebrow">חתימות והחזרות</span><h1>חיילים וציוד אישי</h1><p>{signatures.data?.items.length??0} חתימות במערכת · {signatures.data?.items.filter(x=>x.status==='pending').length??0} ממתינות</p></div><div className="page-actions"><Button onClick={()=>csv(visible)}><Download/>ייצוא</Button></div></header>
    {notice&&<div className="inline-notice" role="status">{notice}<button onClick={()=>setNotice('')}>×</button></div>}
    {mutate.error&&<div className="login-error" role="alert">{mutate.error.message}</div>}
    <div className="toolbar"><SearchInput value={query} onChange={setQuery} placeholder="חיפוש שם, מ״א, מחלקה או טלפון"/><div className="filter-group">{([['all','הכול'],['pending','ממתינים'],['outside','ציוד בחוץ'],['returned','הוחזר']] as const).map(([v,l])=><button key={v} aria-pressed={filter===v} onClick={()=>setFilter(v)}>{l}</button>)}</div><IconButton label="רענון" onClick={()=>signatures.refetch()}><RefreshCw/></IconButton></div>
    <div className="table-card"><table><thead><tr><th>חייל</th><th>מ״א</th><th>מחלקה</th><th>נחתם</th><th>בחוץ</th><th>סטטוס</th><th></th></tr></thead><tbody>{visible.map(row=>{const open=expanded===row.id;return <Fragment key={row.id}><tr className={open?'is-expanded':''}><td><button className="identity-cell" onClick={()=>setExpanded(open?null:row.id)}><Avatar name={row.full_name}/><span><strong>{row.full_name}</strong><small>{row.phone.replace(/(\d{3})\d{4}(\d{3})/,'$1••••$2')}</small></span></button></td><td dir="ltr">{row.personal_id}</td><td>{row.department}</td><td>{new Date(row.signed_at).toLocaleDateString('he-IL')}</td><td><strong className={totalOut(row)?'out-count':''}>{totalOut(row)}</strong></td><td><StatusBadge tone={row.status==='pending'?'warning':totalOut(row)?'neutral':'success'}>{statusLabel(row)}</StatusBadge></td><td><IconButton label="פתיחת פרטים" onClick={()=>setExpanded(open?null:row.id)}><ChevronDown className={open?'rotate':''}/></IconButton></td></tr>{open&&<tr className="detail-row"><td colSpan={7}><div className="soldier-expanded lifecycle-detail">
      <section className="detail-section actions-section"><h3>פעולות מנהל</h3><div className="action-stack">{row.status==='pending'?<><button onClick={()=>mutate.mutate({id:row.id,input:{action:'approve'}})} disabled={mutate.isPending}><Check/>אישור החתימה</button><button className="danger-action" onClick={()=>mutate.mutate({id:row.id,input:{action:'reject'}})} disabled={mutate.isPending}><X/>דחיית החתימה</button></>:<>{totalOut(row)>0&&<button onClick={()=>window.confirm('לזכות את כל הציוד של החתימה?')&&mutate.mutate({id:row.id,input:{action:'return_all'}})}><RotateCcw/>זיכוי מלא</button>}<button onClick={()=>window.open(`/api/v2/documents?key=${encodeURIComponent(row.signature_object_key)}`,'_blank')}><Eye/>צפייה בחתימה</button></>}</div></section>
      <section className="detail-section"><header><h3>פרטי החייל</h3><StatusBadge tone={row.status==='approved'?'success':'warning'}>{row.status==='approved'?'מאושר':'ממתין'}</StatusBadge></header><dl className="detail-grid"><div className="detail-field"><dt>שם</dt><dd>{row.full_name}</dd></div><div className="detail-field"><dt>מספר אישי</dt><dd dir="ltr">{row.personal_id}</dd></div><div className="detail-field"><dt>טלפון</dt><dd dir="ltr">{row.phone}</dd></div><div className="detail-field"><dt>מחלקה</dt><dd>{row.department}</dd></div><div className="detail-field"><dt>נשק</dt><dd dir="ltr">{row.weapon_serial||'—'}</dd></div></dl></section>
      <section className="detail-section licenses-section"><h3>רישיונות</h3>{row.licenses.length?row.licenses.map(license=><article key={license.type}><div><strong>{license.type==='civilian'?'רישיון אזרחי':'רישיון צבאי'}</strong><small>מס׳ {license.license_number} · בתוקף עד {new Date(license.expires_at).toLocaleDateString('he-IL')}</small></div><Button size="sm" onClick={()=>window.open(`/api/v2/documents?key=${encodeURIComponent(license.document_object_key)}`,'_blank')}><Eye/>צפייה</Button></article>):<p className="muted-text">לא צורפו רישיונות.</p>}</section>
      <section className="detail-section equipment-section"><header><h3>ציוד וזיכויים</h3><span>{totalOut(row)} בחוץ</span></header><div className="return-list">{row.lines.map(line=><div key={line.id}><span><strong>{line.name}</strong><small>הוחזרו {line.returned_quantity} מתוך {line.issued_quantity}</small></span><div className="quantity-control"><button disabled={row.status!=='approved'||line.returned_quantity<=0||mutate.isPending} onClick={()=>mutate.mutate({id:row.id,input:{action:'return_item',lineId:line.id,delta:-1}})} aria-label="ביטול זיכוי"><Minus/></button><b>{line.returned_quantity}/{line.issued_quantity}</b><button disabled={row.status!=='approved'||line.returned_quantity>=line.issued_quantity||mutate.isPending} onClick={()=>mutate.mutate({id:row.id,input:{action:'return_item',lineId:line.id,delta:1}})} aria-label="זיכוי פריט"><Plus/></button></div></div>)}</div></section>
    </div></td></tr>}</Fragment>})}</tbody></table>{signatures.isLoading&&<div className="empty-state"><p>טוען חתימות…</p></div>}{!signatures.isLoading&&!visible.length&&<div className="empty-state"><h2>אין חתימות להצגה</h2><p>חתימה חדשה של חייל תופיע כאן.</p></div>}</div></section>}
