import { Check, Eye, RefreshCw, RotateCcw, Search, Wrench, X } from 'lucide-react';
import { useMutation,useQuery,useQueryClient } from '@tanstack/react-query';
import { useMemo,useState } from 'react';
import { Button } from '@/components/ui/Button';
import { StatusBadge } from '@/components/ui/StatusBadge';
import { api } from '@/services/api';

const depositLabels:Record<string,string>={pending:'ממתין לאישור',approved:'נמצא בארמון',returned:'הוחזר לחייל',rejected:'נדחה'};
const faultLabels:Record<string,string>={open:'פתוחה',in_progress:'בטיפול',resolved:'טופלה',closed:'נסגרה'};

export function ArmoryPage(){const client=useQueryClient();const[q,setQ]=useState('');const data=useQuery({queryKey:['weapon-deposits'],queryFn:api.weaponDeposits});const mutation=useMutation({mutationFn:({id,action}:{id:string;action:string})=>api.updateWeaponDeposit(id,action),onSuccess:()=>client.invalidateQueries({queryKey:['weapon-deposits']})});const rows=useMemo(()=>{const n=q.toLowerCase();return(data.data?.items??[]).filter(x=>!n||`${x.full_name} ${x.personal_id} ${x.weapon_serial}`.toLowerCase().includes(n))},[data.data,q]);return <section className="page compact-page"><header className="page-title"><div><span className="eyebrow">נשק ואופטיקה</span><h1>ארמון</h1><p>בקשות אפסון, קליטה והחזרת נשק לבעליו.</p></div></header><div className="module-stats"><article><span>ממתינים</span><strong>{rows.filter(x=>x.status==='pending').length}</strong><small>דורשים אישור</small></article><article><span>בארמון</span><strong>{rows.filter(x=>x.status==='approved').length}</strong><small>הפקדות פעילות</small></article><article><span>הוחזרו</span><strong>{rows.filter(x=>x.status==='returned').length}</strong><small>לבעלים</small></article></div><div className="module-toolbar"><label><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="שם, מ״א או מספר נשק"/></label><Button onClick={()=>data.refetch()}><RefreshCw/>רענון</Button></div>{mutation.error&&<div className="login-error">{mutation.error.message}</div>}<section className="section-card module-table-card"><header><div><h2>בקשות אפסון</h2><p>נשק נרשם בארמון רק לאחר לחיצה על אישור וקליטה.</p></div></header><div className="module-table-wrap"><table><thead><tr><th>חייל</th><th>מ״א</th><th>נשק</th><th>אמר״ל</th><th>כוונת</th><th>סטטוס</th><th>פעולה</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td>{row.full_name}</td><td dir="ltr">{row.personal_id}</td><td dir="ltr">{row.weapon_serial}</td><td dir="ltr">{row.amral_serial||'—'}</td><td dir="ltr">{row.scope_serial||'—'}</td><td><StatusBadge tone={row.status==='pending'?'warning':row.status==='approved'?'success':'neutral'}>{depositLabels[row.status]||row.status}</StatusBadge></td><td><div className="row-actions">{row.status==='pending'&&<><Button size="sm" variant="primary" onClick={()=>mutation.mutate({id:row.id,action:'approve'})}><Check/>אישור וקליטה</Button><Button size="sm" onClick={()=>mutation.mutate({id:row.id,action:'reject'})}><X/>דחייה</Button></>}{row.status==='approved'&&<Button size="sm" onClick={()=>window.confirm('לאשר שהנשק הוחזר לחייל?')&&mutation.mutate({id:row.id,action:'return'})}><RotateCcw/>החזרה לחייל</Button>}</div></td></tr>)}</tbody></table></div>{!rows.length&&<div className="module-empty"><span>אין בקשות אפסון.</span></div>}</section></section>}

export function FaultsPage(){const client=useQueryClient();const[q,setQ]=useState('');const data=useQuery({queryKey:['building-faults'],queryFn:api.buildingFaults});const mutation=useMutation({mutationFn:({id,status}:{id:string;status:string})=>api.updateBuildingFault(id,status),onSuccess:()=>client.invalidateQueries({queryKey:['building-faults']})});const rows=useMemo(()=>{const n=q.toLowerCase();return(data.data?.items??[]).filter(x=>!n||`${x.reporter_name} ${x.location} ${x.category} ${x.description}`.toLowerCase().includes(n))},[data.data,q]);return <section className="page compact-page"><header className="page-title"><div><span className="eyebrow">אחזקה ובינוי</span><h1>תקלות בינוי</h1><p>מעקב מפנייה ועד סיום התיקון.</p></div></header><div className="module-stats"><article><span>פתוחות</span><strong>{rows.filter(x=>x.status==='open').length}</strong><small>טרם הועברו</small></article><article><span>בטיפול</span><strong>{rows.filter(x=>x.status==='in_progress').length}</strong><small>אצל גורם מטפל</small></article><article><span>טופלו</span><strong>{rows.filter(x=>['resolved','closed'].includes(x.status)).length}</strong><small>הושלמו</small></article></div><div className="module-toolbar"><label><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="חיפוש מיקום, מדווח או תיאור"/></label></div><section className="section-card module-table-card"><header><div><h2>יומן תקלות</h2><p>הפרטים המלאים שנשלחו מאזור החייל.</p></div></header><div className="module-table-wrap"><table><thead><tr><th>מיקום</th><th>קטגוריה</th><th>תיאור</th><th>מדווח</th><th>נפתח</th><th>סטטוס</th><th>פעולה</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td><strong>{row.location}</strong></td><td>{row.category}</td><td className="description-cell">{row.description}</td><td>{row.reporter_name}<small>{row.phone}</small></td><td>{new Date(row.created_at).toLocaleDateString('he-IL')}</td><td><StatusBadge tone={row.status==='open'?'warning':row.status==='resolved'?'success':'neutral'}>{faultLabels[row.status]}</StatusBadge></td><td>{row.status==='open'?<Button size="sm" onClick={()=>mutation.mutate({id:row.id,status:'in_progress'})}><Wrench/>העברה לטיפול</Button>:row.status==='in_progress'?<Button size="sm" variant="primary" onClick={()=>mutation.mutate({id:row.id,status:'resolved'})}><Check/>סיום טיפול</Button>:<span className="muted-text">הושלם</span>}</td></tr>)}</tbody></table></div>{!rows.length&&<div className="module-empty"><span>אין תקלות להצגה.</span></div>}</section></section>}

export function LicensesPage(){const data=useQuery({queryKey:['equipment-signatures'],queryFn:api.equipmentSignatures});const rows=(data.data?.items??[]).flatMap(row=>row.licenses.map(license=>({...license,fullName:row.full_name,personalId:row.personal_id,department:row.department})));return <section className="page compact-page"><header className="page-title"><div><span className="eyebrow">מסמכים וכשירות</span><h1>רישיונות נהיגה</h1><p>רישיונות שהועלו בטופס החתימה, משויכים לכרטיס החייל.</p></div></header><section className="section-card module-table-card"><header><div><h2>רישיונות חיילים</h2><p>{rows.length} מסמכים במערכת</p></div></header><div className="module-table-wrap"><table><thead><tr><th>חייל</th><th>מ״א</th><th>מחלקה</th><th>סוג</th><th>מספר</th><th>תוקף</th><th>מסמך</th></tr></thead><tbody>{rows.map((row,i)=><tr key={`${row.personalId}-${row.type}-${i}`}><td>{row.fullName}</td><td dir="ltr">{row.personalId}</td><td>{row.department}</td><td>{row.type==='civilian'?'אזרחי':'צבאי'}</td><td dir="ltr">{row.license_number}</td><td>{new Date(row.expires_at).toLocaleDateString('he-IL')}</td><td><Button size="sm" onClick={()=>window.open(`/api/v2/documents?key=${encodeURIComponent(row.document_object_key)}`,'_blank')}><Eye/>צפייה ברישיון</Button></td></tr>)}</tbody></table></div>{!rows.length&&<div className="module-empty"><span>טרם הועלו רישיונות.</span></div>}</section></section>}
