import { Download, Printer } from 'lucide-react';
import { useQueries, useQuery } from '@tanstack/react-query';
import { Button } from '@/components/ui/Button';
import { api } from '@/services/api';
const modules=['inventory','armory','communications','ammunition','vehicles'];
const moduleNames:Record<string,string>={inventory:'מלאי',armory:'ארמון',communications:'קשר',ammunition:'תחמושת ואלפא',vehicles:'רכב'};
const download=(name:string,rows:string[][])=>{const content='\uFEFF'+rows.map(row=>row.map(v=>`"${v.replaceAll('"','""')}"`).join(',')).join('\n');const url=URL.createObjectURL(new Blob([content],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`armory-${name}-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(url)};
export function ReportsPage({stocktake=false}:{stocktake?:boolean}){const signatures=useQuery({queryKey:['equipment-signatures'],queryFn:api.equipmentSignatures});const assets=useQueries({queries:modules.map(module=>({queryKey:['assets',module],queryFn:()=>api.assets(module)}))});const assetRows=assets.flatMap((q,i)=>(q.data?.items??[]).map(asset=>({...asset,moduleName:moduleNames[modules[i]!]??modules[i]!})));const signatureRows=signatures.data?.items??[];const equipment=signatureRows.flatMap(s=>s.lines.map(line=>({soldier:s.full_name,personalId:s.personal_id,department:s.department,item:line.name,issued:line.issued_quantity,returned:line.returned_quantity,out:line.issued_quantity-line.returned_quantity})));if(stocktake)return <section className="page compact-page"><header className="page-title"><div><span className="eyebrow">ספירת ציוד</span><h1>דו״ח צל״ם</h1><p>תמונת מצב חיה מכל מאגרי הציוד במערכת.</p></div><Button onClick={()=>window.print()}><Printer/>הדפסה / PDF</Button></header><div className="module-stats">{modules.slice(0,3).map(module=><article key={module}><span>{moduleNames[module]}</span><strong>{assetRows.filter(x=>x.module===module).reduce((sum,x)=>sum+x.quantity,0)}</strong><small>יחידות רשומות</small></article>)}</div><section className="section-card module-table-card"><header><div><h2>ספירה מרוכזת</h2><p>מלאי, בחוץ ויתרה זמינה.</p></div></header><div className="module-table-wrap"><table><thead><tr><th>תחום</th><th>פריט</th><th>קטגוריה</th><th>מלאי</th><th>בחוץ</th><th>זמין</th></tr></thead><tbody>{assetRows.map(x=><tr key={x.id}><td>{x.moduleName}</td><td>{x.name}</td><td>{x.category}</td><td>{x.quantity}</td><td>{x.issued_quantity}</td><td><strong>{x.quantity-x.issued_quantity}</strong></td></tr>)}</tbody></table></div></section></section>;
return <section className="page compact-page"><header className="page-title"><div><span className="eyebrow">ניתוח וייצוא</span><h1>דוחות</h1><p>הדוחות נוצרים מנתוני Production העדכניים.</p></div><Button onClick={()=>window.print()}><Printer/>הדפסה / PDF</Button></header><div className="module-stats"><article><span>חיילים עם חתימות</span><strong>{new Set(signatureRows.map(x=>x.personal_id)).size}</strong><small>במערכת</small></article><article><span>פריטי ציוד בחוץ</span><strong>{equipment.reduce((sum,x)=>sum+x.out,0)}</strong><small>אצל חיילים</small></article><article><span>נכסי מלאי</span><strong>{assetRows.length}</strong><small>בכל התחומים</small></article></div><div className="report-actions"><article><h2>מי חתום על מה</h2><p>חייל, מחלקה, פריט, הוחתם, הוחזר ובחוץ.</p><Button onClick={()=>download('equipment-signatures',[['חייל','מ״א','מחלקה','פריט','הוחתם','הוחזר','בחוץ'],...equipment.map(x=>[x.soldier,x.personalId,x.department,x.item,String(x.issued),String(x.returned),String(x.out)])])}><Download/>ייצוא CSV</Button></article><article><h2>מלאי מרוכז</h2><p>כל הנכסים, הכמויות והמיקום בכל המחסנים.</p><Button onClick={()=>download('inventory',[['תחום','פריט','קטגוריה','מלאי','בחוץ','מיקום'],...assetRows.map(x=>[x.moduleName,x.name,x.category,String(x.quantity),String(x.issued_quantity),x.location])])}><Download/>ייצוא CSV</Button></article><article><h2>רשימת נשק</h2><p>נשקים שנקלטו בארמון ומיקומם הנוכחי.</p><Button onClick={()=>download('weapons',[['פריט','מספר סידורי','בעלים','מיקום'],...assetRows.filter(x=>x.module==='armory'&&x.category==='נשק').map(x=>[x.name,x.serial_number??'',x.owner_name??'',x.location])])}><Download/>ייצוא CSV</Button></article></div></section>}
